#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ADL=adl
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     UNAME=linux;;
    Darwin*)    UNAME=mac;;
    CYGWIN*)    
      UNAME=cygwin
      AIR_HOME="$( echo "/${AIR_HOME}" | sed -e 's/\\/\//g' -e 's/://' -e 's/\/\//\//g' )"
      ;;
    MINGW*)     
      UNAME=mingw
      AIR_HOME="$( echo "/${AIR_HOME}" | sed -e 's/\\/\//g' -e 's/://' -e 's/\/\//\//g' )"
      ADL=adl.exe
      ;;
    *)
      UNAME="UNKNOWN:${unameOut}"
      ;;
esac

# if AIR_HOME environment variable is set, look for "adl" in AIR_HOME/bin directory
if [ -z "${ADL_DIR}" ] && [ ! -z "${AIR_HOME}" ]; then
  ADL_DIR="${AIR_HOME}/bin/"
fi

AIR_DIR="$(dirname "$(dirname "$(which "${ADL_DIR}/${ADL}")")")"

"${ADL_DIR}"${ADL} -profile extendedDesktop -nodebug -multi-instance -cmd "${SCRIPT_DIR}/apm.xml" -- \
    -workingdir "$( pwd )" \
    -appdir "${SCRIPT_DIR}" \
    -airdir "${AIR_DIR}" \
    -uname "${UNAME}" \
    "$@"
